connect 'D:\BD\Medshop.fdb' user 'SYSDBA' password 'masterkey';
commit;

insert into Medd values (1,'Regaine',0,60);
insert into Medd values (2,'Lacipil',1,40);
insert into Medd values (3,'Aevit',0,10);
insert into Medd values (4,'Aqua Maris',0,30);
insert into Medd values (5,'Baneocin',0,10);
insert into Medd values (6,'Berocca',0,80);
insert into Medd values (7,'Vibrocil',0,15);
insert into Medd values (8,'Vitrum',0,120);
insert into Medd values (9,'Hexoral',0,40);
insert into Medd values (10,'Hydrocortisone',1,1000);
insert into Medd values (11,'Dimedrol',0,500);
insert into Medd values (12,'Ibuprofen',0,20);
insert into Medd values (13,'Kagocel',0,12);
insert into Medd values (14,'Coldrex',0,50);
insert into Medd values (15,'Nasivin',0,10);

insert into Consigment values (1,'GlaxoSmithKline Pharmaceuticals','ru.gsk.com');
insert into Consigment values (2,'Lumi','www.lumi.spb.ru');
insert into Consigment values (3,'Jadran Galenski Laboratorij','www.jadran.ru');
insert into Consigment values (4,'Sandoz','www.sandoz.ru');
insert into Consigment values (5,'Bayer Sante Familiale','www.bayer.fr');
insert into Consigment values (6,'Novartis Consumer Health','www.novartis.ru');
insert into Consigment values (7,'Unipharm','www.unipharm.ru');
insert into Consigment values (8,'Farmak','farmak.ua');
insert into Consigment values (9,'Dalchimfarm','dhf.khv.ru');
insert into Consigment values (10,'Johnson & Johnson','www.jnj.ru');
insert into Consigment values (11,'Sintez','www.kurgansintez.ru');
insert into Consigment values (12,'Nearmedic','www.nearmedic.ru');
insert into Consigment values (13,'Merck Selbstmedikation GmbH','www.merckselbstmedikation.de');

insert into Delivery values (1,10,1,'01.05.2018');
insert into Delivery values (2,1,2,'01.06.2018');
insert into Delivery values (3,2,3,'01.09.2017');
insert into Delivery values (4,3,4,'01.10.2017');
insert into Delivery values (5,4,5,'01.06.2018');
insert into Delivery values (6,5,6,'01.04.2018');
insert into Delivery values (7,6,7,'31.08.2017');
insert into Delivery values (8,7,8,'01.10.2020');
insert into Delivery values (9,10,9,'31.12.2017');
insert into Delivery values (10,8,10,'01.04.2019');
insert into Delivery values (11,9,11,'03.07.2018');
insert into Delivery values (12,11,12,'01.01.2018');
insert into Delivery values (13,12,13,'01.05.2018');
insert into Delivery values (14,1,14,'01.05.2018');
insert into Delivery values (15,13,15,'01.07.2019');

insert into Clients values (1,5,'Veris');
insert into Clients values (2,7,'Goremykina');
insert into Clients values (3,7,'Smirnov');
insert into Clients values (4,10,'Kalugina');
insert into Clients values (5,12,'Drozdovskii');

insert into Orders values (1,1,0);
insert into Orders values (2,3,4206);
insert into Orders values (3,5,15);
insert into Orders values (4,2,150);
insert into Orders values (5,3,337);
insert into Orders values (6,1,110);

insert into Ord_med values (1,6,6,1);
insert into Ord_med values (2,2,1,3);
insert into Ord_med values (3,4,10,1);
insert into Ord_med values (4,6,3,3);
insert into Ord_med values (5,3,12,1);
insert into Ord_med values (6,5,2,1);

insert into Appointment values (1,'Baldness');
insert into Appointment values (2,'Hypertension');
insert into Appointment values (3,'Arteriosclerosis');
insert into Appointment values (4,'Diseases of nasal cavity');
insert into Appointment values (5,'Adenoiditis');
insert into Appointment values (6,'Skin Infections');
insert into Appointment values (7,'Vitamin deficiency');
insert into Appointment values (8,'Rhinitis');
insert into Appointment values (9,'Sinusitis');
insert into Appointment values (10,'Angina');
insert into Appointment values (11,'Pharyngitis');
insert into Appointment values (12,'Inflammation');
insert into Appointment values (13,'Allergy');
insert into Appointment values (14,'Rheumatoid arthritis');
insert into Appointment values (15,'Radiculitis');
insert into Appointment values (16,'Flu');
insert into Appointment values (17,'Fever heat');
insert into Appointment values (18,'Seasikness');

insert into Appoint_med values (1,1,1);
insert into Appoint_med values (2,2,2);
insert into Appoint_med values (3,3,3);
insert into Appoint_med values (4,4,3);
insert into Appoint_med values (5,5,4);
insert into Appoint_med values (6,6,5);
insert into Appoint_med values (7,7,6);
insert into Appoint_med values (8,8,7);
insert into Appoint_med values (9,9,7);
insert into Appoint_med values (10,7,8);
insert into Appoint_med values (11,10,9);
insert into Appoint_med values (12,11,9);
insert into Appoint_med values (13,12,10);
insert into Appoint_med values (14,13,10);
insert into Appoint_med values (15,13,11);
insert into Appoint_med values (16,18,11);
insert into Appoint_med values (17,14,12);
insert into Appoint_med values (18,15,12);
insert into Appoint_med values (19,16,13);
insert into Appoint_med values (20,16,14);
insert into Appoint_med values (21,17,14);
insert into Appoint_med values (22,8,15);
insert into Appoint_med values (23,9,15);

insert into Constraindications values (1,'Myocardial infarction');
insert into Constraindications values (2,'Abnormal liver function');
insert into Constraindications values (3,'Thyrotoxicosis');
insert into Constraindications values (4,'Pregnancy');
insert into Constraindications values (5,'Extensive skin lesions');
insert into Constraindications values (6,'Atrophic rhinitis');
insert into Constraindications values (7,'Hypersensitivity');
insert into Constraindications values (8,'Systemic mycoses');
insert into Constraindications values (9,'Ulcerative colitis');
insert into Constraindications values (10,'Lactation');
insert into Constraindications values (11,'No');

insert into Const_med values (1,11,1);
insert into Const_med values (2,1,2);
insert into Const_med values (3,2,2);
insert into Const_med values (4,3,3);
insert into Const_med values (5,4,3);
insert into Const_med values (6,11,4);
insert into Const_med values (7,5,5);
insert into Const_med values (8,2,5);
insert into Const_med values (9,11,6);
insert into Const_med values (10,6,7);
insert into Const_med values (11,7,8);
insert into Const_med values (12,11,9);
insert into Const_med values (13,7,10);
insert into Const_med values (14,8,10);
insert into Const_med values (15,4,10);
insert into Const_med values (16,10,10);
insert into Const_med values (18,7,11);
insert into Const_med values (19,7,12);
insert into Const_med values (20,9,12);
insert into Const_med values (21,2,12);
insert into Const_med values (23,4,13);
insert into Const_med values (24,10,13);
insert into Const_med values (25,7,14);
insert into Const_med values (26,11,15);

insert into Side_effects values (1,'Headache');
insert into Side_effects values (2,'Dizziness');
insert into Side_effects values (3,'Nausea');
insert into Side_effects values (4,'Allergic reactions');
insert into Side_effects values (5,'Drowsiness');
insert into Side_effects values (6,'Weakness');
insert into Side_effects values (7,'Anorexia');
insert into Side_effects values (8,'Flatulence');
insert into Side_effects values (9,'Sneezing');
insert into Side_effects values (10,'No');

insert into Eff_med values (1,10,1,0);
insert into Eff_med values (2,1,2,75);
insert into Eff_med values (3,2,2,75);
insert into Eff_med values (4,3,2,25);
insert into Eff_med values (5,10,3,0);
insert into Eff_med values (6,10,4,0);
insert into Eff_med values (7,4,5,25);
insert into Eff_med values (8,10,5,0);
insert into Eff_med values (9,10,6,0);
insert into Eff_med values (10,10,7,0);
insert into Eff_med values (11,4,8,50);
insert into Eff_med values (12,10,9,0);
insert into Eff_med values (13,10,10,0);
insert into Eff_med values (14,5,11,75);
insert into Eff_med values (15,2,11,75);
insert into Eff_med values (16,3,11,75);
insert into Eff_med values (17,6,11,75);
insert into Eff_med values (18,1,11,75);
insert into Eff_med values (19,3,12,75);
insert into Eff_med values (20,7,12,75);
insert into Eff_med values (21,8,12,75);
insert into Eff_med values (22,2,12,75);
insert into Eff_med values (23,1,12,75);
insert into Eff_med values (24,4,12,75);
insert into Eff_med values (25,4,13,50);
insert into Eff_med values (26,4,14,75);
insert into Eff_med values (27,9,15,50);
insert into Eff_med values (28,5,15,25);
insert into Eff_med values (29,1,15,25);
insert into Eff_med values (30,3,15,25);

commit;

select * from Medd;
select * from Consigment;
select * from Delivery;
select * from Clients;
select * from Orders;
select * from Ord_med;
select * from Appointment;
select * from Appoint_med;
select * from Constraindications;
select * from Const_med;
select * from Side_effects;
select * from Eff_med;
